import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '../components/Header';
import HeaderMobile from '../components/Header-mobile';
import MarginWidthWrapper from '../components/margin-width-wrapper';
import SideNav from '../components/SideNav';
import { AuthContextProvider } from '@/context/AuthContext';
import RightSidebar from '@/components/RightSideBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Side Nav w/ Sub Menu',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-white ${inter.className} max-w-7xl mx-auto`}>
        <AuthContextProvider>
          <div className="flex">
            {/* Sidebar */}
            <SideNav />

            {/* Main Content Area */}
            <main className="flex-1 flex flex-col "> {/* Take the remaining space, relative for floating button */}
              <MarginWidthWrapper>
                <Header />
                <HeaderMobile />
                <div className='flex '>
                  {children}
                  <RightSidebar />
                </div>
              </MarginWidthWrapper>
            </main>
          </div>
        </AuthContextProvider>
      </body>
    </html>
  );
}
